### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by lenadax** [rohberg/volto-slate-glossary#7]
React is expecting a unique key for each list item in TextWithGlossaryTooltips, resulting in a warning.

Browser console output:
```
index.js:1 Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at TextWithGlossaryTooltips (http://localhost:3001/static/js/client.js:77308:3)
    at span
    at Leaf (http://localhost:3001/static/js/client.js:111159:7)
    at Leaf (http://localhost:3001/static/js/client.js:330191:5)
    at span
    at Text (http://localhost:3001/static/js/client.js:330308:5)
    at p
    at p (http://localhost:3001/static/js/client.js:104179:5)
    at Element (http://localhost:3001/static/js/client.js:111124:7)
    at Element (http://localhost:3001/static/js/client.js:330369:5)
    at Children (http://localhost:3001/static/js/client.js:330864:160)
    at div
    at RestoreDOM (http://localhost:3001/static/js/client.js:330852:5)
    at Editable (http://localhost:3001/static/js/client.js:330871:84)
    at Slate (http://localhost:3001/static/js/client.js:332451:5)
    at div
    at SlateEditor (http://localhost:3001/static/js/client.js:103321:5)
    at div
    at div
    at div
    at InfoBox (http://localhost:3001/static/js/client.js:221959:5)
    at http://localhost:3001/static/js/client.js:190613:5
    at StyleWrapper (http://localhost:3001/static/js/client.js:131689:5)
    at MaybeWrap (http://localhost:3001/static/js/client.js:154584:7)
    at div
    at MaybeWrap (http://localhost:3001/static/js/client.js:154584:7)
    at RenderBlocks (http://localhost:3001/static/js/client.js:216695:5)
    at div
    at $2e5fe81f2b094176$export$42a852a2b6b56249 (http://localhost:3001/static/js/client.js:362383:17)
    at DefaultView (http://localhost:3001/static/js/client.js:179013:5)
    at div
    at View (http://localhost:3001/static/js/client.js:180859:5)
    at ConnectFunction (http://localhost:3001/static/js/client.js:282065:103)
    at injectIntl(Connect(View))
    at Route (http://localhost:3001/static/js/client.js:285206:29)
    at Switch (http://localhost:3001/static/js/client.js:285412:29)
    at main
    at div
    at Segment (http://localhost:3001/static/js/client.js:310925:24)
    at MultilingualRedirector (http://localhost:3001/static/js/client.js:173789:5)
    at PluggablesProvider (http://localhost:3001/static/js/client.js:156400:3)
    at App (http://localhost:3001/static/js/client.js:168564:5)
    at ConnectFunction (http://localhost:3001/static/js/client.js:282065:103)
    at injectIntl(Connect(App))
    at ConnectFunction (http://localhost:3001/static/js/client.js:282065:103)
    at Route (http://localhost:3001/static/js/client.js:285206:29)
    at Switch (http://localhost:3001/static/js/client.js:285412:29)
    at Route (http://localhost:3001/static/js/client.js:285206:29)
    at AsyncConnect (http://localhost:3001/static/js/client.js:187926:5)
    at AsyncConnectWithContext (http://localhost:3001/static/js/client.js:188044:7)
    at C (http://localhost:3001/static/js/client.js:285467:37)
    at ConnectFunction (http://localhost:3001/static/js/client.js:282065:103)
    at ScrollToTop (http://localhost:3001/static/js/client.js:195360:1)
    at ConnectFunction (http://localhost:3001/static/js/client.js:282065:103)
    at Router (http://localhost:3001/static/js/client.js:284835:30)
    at ConnectedRouter (http://localhost:3001/static/js/client.js:10929:7)
    at ConnectedRouterWithContext (http://localhost:3001/static/js/client.js:11035:25)
    at ConnectFunction (http://localhost:3001/static/js/client.js:282065:103)
    at IntlProvider (http://localhost:3001/static/js/client.js:279666:9)
    at ConnectFunction (http://localhost:3001/static/js/client.js:282065:103)
    at Provider (http://localhost:3001/static/js/client.js:281774:3)
    at CookiesProvider (http://localhost:3001/static/js/client.js:232641:28)
```

**Comment by ksuess** [comment]
Hm, can't reproduce this. Do you have some more information? Some example text and glossary terms maybe.

**Comment by ksuess** [comment]
Note that the add-on is currently being refactored. The release is only a few hours away.

**Comment by ksuess** [comment]
This issue seems to be resolved. Feel free to reopen if necessary.

**Comment by ksuess** [comment]
@lenadax would you mind giving this repo a star, merci!
